### ISSUE TITLE
Разработать дизайн темы для документации NextGIS

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/docs_ng#2]
Перенес из https://github.com/nextgis/docs_ngweb/issues/2

**Comment by trolleway** [comment]
Пожелания
- Настроить подписи картинок, так что бы в тексте писалось "см. рис. 1", а в подписи под картинкой - "Рис. 1" - с большой буквы
- :guilabel: обрамлялся бы кавычками (?)

**Comment by BishopGIS** [comment]
@trolleway, к этому тикету это не относится. Там цветовые схемы, шрифты и т.п. 
Вынеси это отдельным тикетом с пометкой enhancement

**Comment by BishopGIS** [comment]
Сейчас еще в теме в шапку вынесены переключения языков RU/EN которые представляеют собой ссылку на docs.nextgis.ru и docs.nextgis.com соответственно.

**Comment by Kinda-me** [comment]
Вариант новой html-темы для документации (с нормальным выделением guilabels) - https://github.com/snide/sphinx_rtd_theme

**Comment by BishopGIS** [comment]
Я подключил тему, но то что хотелось (нормальным выделением guilabels) там нет.
Вот скрины.

![2016-05-29 00-51-51](https://cloud.githubusercontent.com/assets/1708122/15630213/1107abe8-2541-11e6-8da8-c32d8cedc8ba.png)

![2016-05-29 00-53-36](https://cloud.githubusercontent.com/assets/1708122/15630214/110abf68-2541-11e6-9aaa-1a105fb4bf4e.png)

![2016-05-29 00-57-48](https://cloud.githubusercontent.com/assets/1708122/15630215/110ad76e-2541-11e6-9b1c-a30fa76de502.png)

**Comment by Kinda-me** [comment]
Оказывается до сих пор этот пулл реквест не смержили -  https://github.com/snide/sphinx_rtd_theme/pull/279/commits

Я за то, чтобы все равно перейти на эту тему (если никаких существенных багов не вылезло).

**Comment by BishopGIS** [comment]
Надо 2 вещи добавить в эту тему:
1. Show/Edit on github
2. Переключение языков

С первым вроде надо добавить туда, где view source (сверху слева).
А со вторым я даже не знаю куда пихать. Возможно туда, где nextgis, версия и поиск (справа вверху).

**Comment by BishopGIS** [comment]
Да, я ставил из pip согласно их же инструкции, так что после того как смержут еще надо будет ждать когда в pip закинут.

**Comment by Kinda-me** [comment]
1. Да, Edit on Github надо сделать как тут на демо - http://docs.readthedocs.io/en/latest/
2. Я так понимаю, переключалка языков есть стандартная, в нижнем левом углу должна появиться - http://read-the-docs.readthedocs.io/en/latest/localization.html#project-with-multiple-translations

**Comment by BishopGIS** [comment]
- 2. Это не стандартная штука. Ее в теме нет. Это я так понимаю самого сервиса RtD кастомизация.

**Comment by BishopGIS** [comment]
В общем я все проблемы решил. Выглядит вот так:

![2016-05-31 00-48-33](https://cloud.githubusercontent.com/assets/1708122/15658872/1d07d466-26d3-11e6-8c23-41d0e32f8367.png)

![2016-05-31 00-56-07](https://cloud.githubusercontent.com/assets/1708122/15658873/1d0922f8-26d3-11e6-91f2-69d2734ceb1a.png)
