### ISSUE TITLE
Разный видимый размер картинок в html и pdf

### ISSUE THREAD

**Issue by trolleway** [nextgis/docs_ng#4]
Если открыть на экране справку в html и справку в pdf, то наблюдаемый размер картинок будет разным.
Можно сказать, что pdf - предназначен только для печати, но вот некоторые люди почему-то смотрят его на экране. 

Что делать?

**Comment by BishopGIS** [comment]
Не уловил суть проблемы. Если надо сделать разного размера картинки используй тег:

```
.. only:: html [latex, epub и т.п.]
```

Что помечено этим тегом будет попадать только в соответствующий билдер документации.
Примеры такого есть - поищи поиском по rst

**Comment by trolleway** [comment]
Не, тогда им пришлось бы помечать абсолютно все картинки. По логике - надо генерировать pdf для экрана, и отдельный pdf для печати, хотя я не понимаю тогда, в чём его межплатформенность.

**Comment by BishopGIS** [comment]
Нету такого pdf для экрана - я его воспринимаю только для печати, ну офлайн чтение еще. Мне кажется вопрос качества картинок - наверное надо в настройках выставить где-то  в conf.py. Но это увеличит размер файла. Пока не уверен, что это необходимо.

**Comment by BishopGIS** [comment]
Надо размеры картинок указывать в сантиметрах, тогда будет все ок. См. доки по мобильному.
